import React from 'react'

// MUI Icons
import {
  Home,
  Settings,
  Favorite,
  Star,
  Camera,
  CheckCircle,
  Add,
  Remove,
  Close,
  Search,
  Menu,
  MoreVert,
  Edit,
  Delete,
  Save,
  AccountCircle,
  Visibility,
  VisibilityOff,
  Refresh,
  ArrowBack,
  ArrowForward,
  ArrowUpward,
  ArrowDownward,
  FileDownload,
  FileUpload,
  Share,
  ContentCopy,
  Link as LinkIcon,
  Lock,
  Public,
  Person,
  Group,
  Notifications,
  Mail,
  Phone,
  Place,
  CalendarToday,
  AccessTime,
  Cloud,
  Brightness4,
  WbSunny,
  FilterList,
  Sort,
  BarChart,
  PieChart,
  Timeline,
  Build,
  Code,
  BugReport,
  Dashboard,
  List as ListIcon,
} from '@mui/icons-material'

// Lucide-React Icons
import {
  Home as LucideHome,
  Settings as LucideSettings,
  Star as LucideStar,
  Heart as LucideHeart,
  Camera as LucideCamera,
  CheckCircle2,
  Plus,
  Minus,
  X,
  Search as LucideSearch,
  Menu as LucideMenu,
  MoreVertical,
  FilePenLine,
  Trash2,
  Save as LucideSave,
  UserCircle2,
  Eye,
  EyeOff,
  RefreshCcw,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  Download,
  Upload,
  Share2,
  Copy,
  Link2,
  Lock as LucideLock,
  Globe,
  Users,
  Bell,
  Mail as LucideMail,
  Phone as LucidePhone,
  MapPin,
  Calendar,
  Clock,
  Cloud as LucideCloud,
  Moon,
  Sun,
  Filter,
  ArrowUpDown,
  BarChart2,
  PieChart as LucidePieChart,
  LineChart,
  Wrench,
  Code2,
  Bug,
  LayoutDashboard,
  List as LucideList,
  Activity,
  Airplay,
  AlarmClock,
  AlertCircle,
  AlignCenter,
  AlignJustify,
  AlignLeft,
  AlignRight,
  Anchor,
  Aperture,
  Archive,
  ArrowBigDown,
  ArrowBigLeft,
  ArrowBigRight,
  ArrowBigUp,
  Asterisk,
  AtSign,
  Award,
  Axe,
  Banknote,
  Beaker,
  BellRing,
  Bike,
  Binary,
  Bitcoin,
  Bomb,
  Bone,
  Book,
  Bookmark,
  Bot,
  Box,
  Briefcase,
  Brush,
  Calculator,
  CalendarCheck,
  CameraOff,
  CandlestickChart,
  Cast,
  Cat,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsDown,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUp,
  Chrome,
  Clipboard,
  CloudDrizzle,
  CloudLightning,
  CloudRain,
  CloudSnow,
  Cog,
  Coins,
  Columns,
  Command,
  Compass,
  Contact,
  Contrast,
  Cookie,
  Copyright,
  CornerDownLeft,
  CornerDownRight,
  CornerLeftDown,
  CornerLeftUp,
  CornerRightDown,
  CornerRightUp,
  CornerUpLeft,
  CornerUpRight,
  Cpu,
  CreativeCommons,
  CreditCard,
  Crop,
  Cross,
  Crosshair,
  Crown,
  CupSoda,
  Currency,
  Database,
  Diamond,
  Dice1,
  Dice2,
  Dice3,
  Dice4,
  Dice5,
  Dice6,
  Disc,
  Dog,
  DollarSign,
  DoorClosed,
  DoorOpen,
  Dribbble,
  Droplet,
  Eraser,
  Euro,
  ExternalLink,
  Facebook,
  FastForward,
  Feather,
  Figma,
  File,
  FileArchive,
  FileAudio,
  FileBadge,
  FileCheck,
  FileCode,
  FileDigit,
  FileDown,
  FileEdit,
  FileHeart,
  FileImage,
  FileInput,
  FileJson,
  FileKey,
  FileLock,
  FileMinus,
  FileOutput,
  FilePlus,
  FileQuestion,
  FileScan,
  FileSearch,
  FileSymlink,
  FileText,
  FileUp,
  FileVideo,
  FileVolume,
  FileWarning,
  FileX,
  Files,
  Film,
  Flag,
  Flame,
  Flashlight,
  FlashlightOff,
  Folder,
  FolderArchive,
  FolderCheck,
  FolderClock,
  FolderClosed,
  FolderCog,
  FolderDown,
  FolderEdit,
  FolderGit,
  FolderGit2,
  FolderHeart,
  FolderInput,
  FolderKey,
  FolderLock,
  FolderMinus,
  FolderOpen,
  FolderOutput,
  FolderPlus,
  FolderRoot,
  FolderSearch,
  FolderSymlink,
  FolderTree,
  FolderUp,
  FolderX,
  Folders,
  Footprints,
  Forklift,
  FormInput,
  Forward,
  Frame,
  Frown,
  Fuel,
  FunctionSquare,
  Gamepad,
  Gamepad2,
  Gauge,
  Gavel,
  Gem,
  Ghost,
  Gift,
  GitBranch,
  GitBranchPlus,
  GitCommit,
  GitCompare,
  GitFork,
  GitMerge,
  GitPullRequest,
  GitPullRequestClosed,
  GitPullRequestDraft,
  Github,
  Gitlab,
  GlassWater,
  Glasses,
  Globe2,
  Grab,
  GraduationCap,
  Grape,
  Grid,
  GripHorizontal,
  GripVertical,
  Hammer,
  Hand,
  HandMetal,
  HardDrive,
  HardHat,
  Hash,
  Haze,
  Heading,
  Heading1,
  Heading2,
  Heading3,
  Heading4,
  Heading5,
  Heading6,
  Headphones,
  HeartCrack,
  HeartHandshake,
  HeartOff,
  HelpCircle,
  HelpingHand,
  Hexagon,
  Highlighter,
  History,
  Hotel,
  Hourglass,
  IceCream,
  Image,
  ImageMinus,
  ImageOff,
  ImagePlus,
  Import,
  Inbox,
  Indent,
  IndianRupee,
  Info,
  Inspect,
  Instagram,
  Italic,
  IterationCcw,
  IterationCw,
  JapaneseYen,
  Joystick,
  Key,
  Keyboard,
  Lamp,
  LampCeiling,
  LampDesk,
  LampFloor,
  LampWallDown,
  LampWallUp,
  Landmark,
  Languages,
  Laptop,
  Laptop2,
  Lasso,
  LassoSelect,
  Laugh,
  Layers,
} from 'lucide-react'

export interface IconInfo {
  name: string
  Component: React.ElementType | null
  source: 'lucide-react' | '@mui/icons-material' | null
  tags: string[]
}

// 아이콘 이름(PascalCase)을 키로 사용하는 Record 자료구조
export const iconRecord: Record<string, IconInfo> = {
  // MUI Icons (50개)
  Home: {
    name: 'Home',
    Component: Home,
    source: '@mui/icons-material',
    tags: ['home', 'house', 'main', 'building'],
  },
  Settings: {
    name: 'Settings',
    Component: Settings,
    source: '@mui/icons-material',
    tags: ['settings', 'options', 'gear', 'configuration'],
  },
  Favorite: {
    name: 'Favorite',
    Component: Favorite,
    source: '@mui/icons-material',
    tags: ['favorite', 'heart', 'like', 'love'],
  },
  Star: {
    name: 'Star',
    Component: Star,
    source: '@mui/icons-material',
    tags: ['star', 'rate', 'favorite', 'highlight'],
  },
  Camera: {
    name: 'Camera',
    Component: Camera,
    source: '@mui/icons-material',
    tags: ['camera', 'photo', 'picture', 'image'],
  },
  CheckCircle: {
    name: 'CheckCircle',
    Component: CheckCircle,
    source: '@mui/icons-material',
    tags: ['check', 'circle', 'done', 'complete', 'ok'],
  },
  Add: {
    name: 'Add',
    Component: Add,
    source: '@mui/icons-material',
    tags: ['add', 'plus', 'new', 'create'],
  },
  Remove: {
    name: 'Remove',
    Component: Remove,
    source: '@mui/icons-material',
    tags: ['remove', 'minus', 'delete'],
  },
  Close: {
    name: 'Close',
    Component: Close,
    source: '@mui/icons-material',
    tags: ['close', 'exit', 'cancel', 'x'],
  },
  Search: {
    name: 'Search',
    Component: Search,
    source: '@mui/icons-material',
    tags: ['search', 'find', 'magnifying glass'],
  },
  Menu: {
    name: 'Menu',
    Component: Menu,
    source: '@mui/icons-material',
    tags: ['menu', 'hamburger', 'navigation', 'list'],
  },
  MoreVert: {
    name: 'MoreVert',
    Component: MoreVert,
    source: '@mui/icons-material',
    tags: ['more', 'options', 'dots', 'vertical'],
  },
  Edit: {
    name: 'Edit',
    Component: Edit,
    source: '@mui/icons-material',
    tags: ['edit', 'pencil', 'write', 'modify'],
  },
  Delete: {
    name: 'Delete',
    Component: Delete,
    source: '@mui/icons-material',
    tags: ['delete', 'trash', 'remove', 'bin'],
  },
  Save: {
    name: 'Save',
    Component: Save,
    source: '@mui/icons-material',
    tags: ['save', 'disk', 'floppy'],
  },
  AccountCircle: {
    name: 'AccountCircle',
    Component: AccountCircle,
    source: '@mui/icons-material',
    tags: ['account', 'user', 'profile', 'person', 'circle'],
  },
  Visibility: {
    name: 'Visibility',
    Component: Visibility,
    source: '@mui/icons-material',
    tags: ['visibility', 'eye', 'show', 'view'],
  },
  VisibilityOff: {
    name: 'VisibilityOff',
    Component: VisibilityOff,
    source: '@mui/icons-material',
    tags: ['visibility', 'eye', 'hide', 'hidden'],
  },
  Refresh: {
    name: 'Refresh',
    Component: Refresh,
    source: '@mui/icons-material',
    tags: ['refresh', 'reload', 'sync'],
  },
  ArrowBack: {
    name: 'ArrowBack',
    Component: ArrowBack,
    source: '@mui/icons-material',
    tags: ['arrow', 'back', 'left', 'previous'],
  },
  ArrowForward: {
    name: 'ArrowForward',
    Component: ArrowForward,
    source: '@mui/icons-material',
    tags: ['arrow', 'forward', 'right', 'next'],
  },
  ArrowUpward: {
    name: 'ArrowUpward',
    Component: ArrowUpward,
    source: '@mui/icons-material',
    tags: ['arrow', 'up', 'upward'],
  },
  ArrowDownward: {
    name: 'ArrowDownward',
    Component: ArrowDownward,
    source: '@mui/icons-material',
    tags: ['arrow', 'down', 'downward'],
  },
  FileDownload: {
    name: 'FileDownload',
    Component: FileDownload,
    source: '@mui/icons-material',
    tags: ['download', 'file', 'save', 'import'],
  },
  FileUpload: {
    name: 'FileUpload',
    Component: FileUpload,
    source: '@mui/icons-material',
    tags: ['upload', 'file', 'export', 'send'],
  },
  Share: {
    name: 'Share',
    Component: Share,
    source: '@mui/icons-material',
    tags: ['share', 'connect', 'social'],
  },
  ContentCopy: {
    name: 'ContentCopy',
    Component: ContentCopy,
    source: '@mui/icons-material',
    tags: ['copy', 'duplicate', 'clone', 'paste'],
  },
  LinkIcon: {
    name: 'LinkIcon',
    Component: LinkIcon,
    source: '@mui/icons-material',
    tags: ['link', 'url', 'chain'],
  },
  Lock: {
    name: 'Lock',
    Component: Lock,
    source: '@mui/icons-material',
    tags: ['lock', 'secure', 'password', 'private'],
  },
  Public: {
    name: 'Public',
    Component: Public,
    source: '@mui/icons-material',
    tags: ['public', 'globe', 'world', 'earth'],
  },
  Person: {
    name: 'Person',
    Component: Person,
    source: '@mui/icons-material',
    tags: ['person', 'user', 'profile', 'human'],
  },
  Group: {
    name: 'Group',
    Component: Group,
    source: '@mui/icons-material',
    tags: ['group', 'users', 'team', 'people'],
  },
  Notifications: {
    name: 'Notifications',
    Component: Notifications,
    source: '@mui/icons-material',
    tags: ['notifications', 'bell', 'alert', 'alarm'],
  },
  Mail: {
    name: 'Mail',
    Component: Mail,
    source: '@mui/icons-material',
    tags: ['mail', 'email', 'inbox', 'message'],
  },
  Phone: {
    name: 'Phone',
    Component: Phone,
    source: '@mui/icons-material',
    tags: ['phone', 'call', 'telephone', 'contact'],
  },
  Place: {
    name: 'Place',
    Component: Place,
    source: '@mui/icons-material',
    tags: ['place', 'location', 'map', 'pin', 'address'],
  },
  CalendarToday: {
    name: 'CalendarToday',
    Component: CalendarToday,
    source: '@mui/icons-material',
    tags: ['calendar', 'date', 'month', 'event'],
  },
  AccessTime: {
    name: 'AccessTime',
    Component: AccessTime,
    source: '@mui/icons-material',
    tags: ['time', 'clock', 'hour', 'watch'],
  },
  Cloud: {
    name: 'Cloud',
    Component: Cloud,
    source: '@mui/icons-material',
    tags: ['cloud', 'weather', 'sky'],
  },
  Brightness4: {
    name: 'Brightness4',
    Component: Brightness4,
    source: '@mui/icons-material',
    tags: ['brightness', 'dark', 'mode', 'theme', 'moon'],
  },
  WbSunny: {
    name: 'WbSunny',
    Component: WbSunny,
    source: '@mui/icons-material',
    tags: ['sun', 'light', 'mode', 'theme', 'sunny'],
  },
  FilterList: {
    name: 'FilterList',
    Component: FilterList,
    source: '@mui/icons-material',
    tags: ['filter', 'list', 'sort', 'options'],
  },
  Sort: {
    name: 'Sort',
    Component: Sort,
    source: '@mui/icons-material',
    tags: ['sort', 'order', 'arrange', 'list'],
  },
  BarChart: {
    name: 'BarChart',
    Component: BarChart,
    source: '@mui/icons-material',
    tags: ['chart', 'bar', 'graph', 'statistics'],
  },
  PieChart: {
    name: 'PieChart',
    Component: PieChart,
    source: '@mui/icons-material',
    tags: ['chart', 'pie', 'graph', 'statistics'],
  },
  Timeline: {
    name: 'Timeline',
    Component: Timeline,
    source: '@mui/icons-material',
    tags: ['timeline', 'graph', 'line', 'history'],
  },
  Build: {
    name: 'Build',
    Component: Build,
    source: '@mui/icons-material',
    tags: ['build', 'wrench', 'tool', 'settings'],
  },
  Code: {
    name: 'Code',
    Component: Code,
    source: '@mui/icons-material',
    tags: ['code', 'developer', 'programming', 'embed'],
  },
  BugReport: {
    name: 'BugReport',
    Component: BugReport,
    source: '@mui/icons-material',
    tags: ['bug', 'report', 'issue', 'debug'],
  },
  Dashboard: {
    name: 'Dashboard',
    Component: Dashboard,
    source: '@mui/icons-material',
    tags: ['dashboard', 'grid', 'layout'],
  },
  ListIcon: {
    name: 'ListIcon',
    Component: ListIcon,
    source: '@mui/icons-material',
    tags: ['list', 'todo', 'checklist', 'items'],
  },

  // Lucide-React Icons (250개)
  LucideHome: {
    name: 'LucideHome',
    Component: LucideHome,
    source: 'lucide-react',
    tags: ['home', 'house', 'main'],
  },
  LucideSettings: {
    name: 'LucideSettings',
    Component: LucideSettings,
    source: 'lucide-react',
    tags: ['settings', 'options', 'gear'],
  },
  LucideStar: {
    name: 'LucideStar',
    Component: LucideStar,
    source: 'lucide-react',
    tags: ['star', 'rate', 'favorite'],
  },
  LucideHeart: {
    name: 'LucideHeart',
    Component: LucideHeart,
    source: 'lucide-react',
    tags: ['heart', 'like', 'love'],
  },
  LucideCamera: {
    name: 'LucideCamera',
    Component: LucideCamera,
    source: 'lucide-react',
    tags: ['camera', 'photo'],
  },
  CheckCircle2: {
    name: 'CheckCircle2',
    Component: CheckCircle2,
    source: 'lucide-react',
    tags: ['check', 'circle', 'done'],
  },
  Plus: {
    name: 'Plus',
    Component: Plus,
    source: 'lucide-react',
    tags: ['add', 'new', 'create'],
  },
  Minus: {
    name: 'Minus',
    Component: Minus,
    source: 'lucide-react',
    tags: ['remove', 'delete'],
  },
  X: {
    name: 'X',
    Component: X,
    source: 'lucide-react',
    tags: ['close', 'exit', 'cancel'],
  },
  LucideSearch: {
    name: 'LucideSearch',
    Component: LucideSearch,
    source: 'lucide-react',
    tags: ['search', 'find'],
  },
  LucideMenu: {
    name: 'LucideMenu',
    Component: LucideMenu,
    source: 'lucide-react',
    tags: ['menu', 'navigation', 'list'],
  },
  MoreVertical: {
    name: 'MoreVertical',
    Component: MoreVertical,
    source: 'lucide-react',
    tags: ['more', 'options', 'dots'],
  },
  FilePenLine: {
    name: 'FilePenLine',
    Component: FilePenLine,
    source: 'lucide-react',
    tags: ['edit', 'write', 'modify'],
  },
  Trash2: {
    name: 'Trash2',
    Component: Trash2,
    source: 'lucide-react',
    tags: ['delete', 'trash', 'remove'],
  },
  LucideSave: {
    name: 'LucideSave',
    Component: LucideSave,
    source: 'lucide-react',
    tags: ['save', 'disk'],
  },
  UserCircle2: {
    name: 'UserCircle2',
    Component: UserCircle2,
    source: 'lucide-react',
    tags: ['user', 'profile', 'person'],
  },
  Eye: {
    name: 'Eye',
    Component: Eye,
    source: 'lucide-react',
    tags: ['eye', 'show', 'view'],
  },
  EyeOff: {
    name: 'EyeOff',
    Component: EyeOff,
    source: 'lucide-react',
    tags: ['eye', 'hide', 'hidden'],
  },
  RefreshCcw: {
    name: 'RefreshCcw',
    Component: RefreshCcw,
    source: 'lucide-react',
    tags: ['refresh', 'reload', 'sync'],
  },
  ArrowLeft: {
    name: 'ArrowLeft',
    Component: ArrowLeft,
    source: 'lucide-react',
    tags: ['arrow', 'back', 'left'],
  },
  ArrowRight: {
    name: 'ArrowRight',
    Component: ArrowRight,
    source: 'lucide-react',
    tags: ['arrow', 'forward', 'right'],
  },
  ArrowUp: {
    name: 'ArrowUp',
    Component: ArrowUp,
    source: 'lucide-react',
    tags: ['arrow', 'up'],
  },
  ArrowDown: {
    name: 'ArrowDown',
    Component: ArrowDown,
    source: 'lucide-react',
    tags: ['arrow', 'down'],
  },
  Download: {
    name: 'Download',
    Component: Download,
    source: 'lucide-react',
    tags: ['download', 'save'],
  },
  Upload: {
    name: 'Upload',
    Component: Upload,
    source: 'lucide-react',
    tags: ['upload', 'send'],
  },
  Share2: {
    name: 'Share2',
    Component: Share2,
    source: 'lucide-react',
    tags: ['share', 'connect'],
  },
  Copy: {
    name: 'Copy',
    Component: Copy,
    source: 'lucide-react',
    tags: ['copy', 'duplicate'],
  },
  Link2: {
    name: 'Link2',
    Component: Link2,
    source: 'lucide-react',
    tags: ['link', 'url'],
  },
  LucideLock: {
    name: 'LucideLock',
    Component: LucideLock,
    source: 'lucide-react',
    tags: ['lock', 'secure', 'private'],
  },
  Globe: {
    name: 'Globe',
    Component: Globe,
    source: 'lucide-react',
    tags: ['globe', 'world', 'public'],
  },
  Users: {
    name: 'Users',
    Component: Users,
    source: 'lucide-react',
    tags: ['users', 'team', 'people'],
  },
  Bell: {
    name: 'Bell',
    Component: Bell,
    source: 'lucide-react',
    tags: ['bell', 'alert', 'notification'],
  },
  LucideMail: {
    name: 'LucideMail',
    Component: LucideMail,
    source: 'lucide-react',
    tags: ['mail', 'email', 'message'],
  },
  LucidePhone: {
    name: 'LucidePhone',
    Component: LucidePhone,
    source: 'lucide-react',
    tags: ['phone', 'call', 'contact'],
  },
  MapPin: {
    name: 'MapPin',
    Component: MapPin,
    source: 'lucide-react',
    tags: ['location', 'map', 'pin'],
  },
  Calendar: {
    name: 'Calendar',
    Component: Calendar,
    source: 'lucide-react',
    tags: ['calendar', 'date', 'event'],
  },
  Clock: {
    name: 'Clock',
    Component: Clock,
    source: 'lucide-react',
    tags: ['time', 'clock', 'hour'],
  },
  LucideCloud: {
    name: 'LucideCloud',
    Component: LucideCloud,
    source: 'lucide-react',
    tags: ['cloud', 'weather'],
  },
  Moon: {
    name: 'Moon',
    Component: Moon,
    source: 'lucide-react',
    tags: ['moon', 'dark', 'theme'],
  },
  Sun: {
    name: 'Sun',
    Component: Sun,
    source: 'lucide-react',
    tags: ['sun', 'light', 'theme'],
  },
  Filter: {
    name: 'Filter',
    Component: Filter,
    source: 'lucide-react',
    tags: ['filter', 'sort'],
  },
  ArrowUpDown: {
    name: 'ArrowUpDown',
    Component: ArrowUpDown,
    source: 'lucide-react',
    tags: ['sort', 'order'],
  },
  BarChart2: {
    name: 'BarChart2',
    Component: BarChart2,
    source: 'lucide-react',
    tags: ['chart', 'bar', 'graph'],
  },
  LucidePieChart: {
    name: 'LucidePieChart',
    Component: LucidePieChart,
    source: 'lucide-react',
    tags: ['chart', 'pie', 'graph'],
  },
  LineChart: {
    name: 'LineChart',
    Component: LineChart,
    source: 'lucide-react',
    tags: ['chart', 'line', 'graph'],
  },
  Wrench: {
    name: 'Wrench',
    Component: Wrench,
    source: 'lucide-react',
    tags: ['wrench', 'tool', 'build'],
  },
  Code2: {
    name: 'Code2',
    Component: Code2,
    source: 'lucide-react',
    tags: ['code', 'developer'],
  },
  Bug: {
    name: 'Bug',
    Component: Bug,
    source: 'lucide-react',
    tags: ['bug', 'issue', 'debug'],
  },
  LayoutDashboard: {
    name: 'LayoutDashboard',
    Component: LayoutDashboard,
    source: 'lucide-react',
    tags: ['dashboard', 'grid'],
  },
  LucideList: {
    name: 'LucideList',
    Component: LucideList,
    source: 'lucide-react',
    tags: ['list', 'todo'],
  },
  Activity: {
    name: 'Activity',
    Component: Activity,
    source: 'lucide-react',
    tags: ['activity', 'pulse', 'health'],
  },
  Airplay: {
    name: 'Airplay',
    Component: Airplay,
    source: 'lucide-react',
    tags: ['airplay', 'stream', 'cast'],
  },
  AlarmClock: {
    name: 'AlarmClock',
    Component: AlarmClock,
    source: 'lucide-react',
    tags: ['alarm', 'clock'],
  },
  AlertCircle: {
    name: 'AlertCircle',
    Component: AlertCircle,
    source: 'lucide-react',
    tags: ['alert', 'warning', 'danger'],
  },
  AlignCenter: {
    name: 'AlignCenter',
    Component: AlignCenter,
    source: 'lucide-react',
    tags: ['align', 'center', 'text'],
  },
  AlignJustify: {
    name: 'AlignJustify',
    Component: AlignJustify,
    source: 'lucide-react',
    tags: ['align', 'justify', 'text'],
  },
  AlignLeft: {
    name: 'AlignLeft',
    Component: AlignLeft,
    source: 'lucide-react',
    tags: ['align', 'left', 'text'],
  },
  AlignRight: {
    name: 'AlignRight',
    Component: AlignRight,
    source: 'lucide-react',
    tags: ['align', 'right', 'text'],
  },
  Anchor: {
    name: 'Anchor',
    Component: Anchor,
    source: 'lucide-react',
    tags: ['anchor', 'link'],
  },
  Aperture: {
    name: 'Aperture',
    Component: Aperture,
    source: 'lucide-react',
    tags: ['aperture', 'camera', 'photo'],
  },
  Archive: {
    name: 'Archive',
    Component: Archive,
    source: 'lucide-react',
    tags: ['archive', 'box', 'storage'],
  },
  ArrowBigDown: {
    name: 'ArrowBigDown',
    Component: ArrowBigDown,
    source: 'lucide-react',
    tags: ['arrow', 'big', 'down'],
  },
  ArrowBigLeft: {
    name: 'ArrowBigLeft',
    Component: ArrowBigLeft,
    source: 'lucide-react',
    tags: ['arrow', 'big', 'left'],
  },
  ArrowBigRight: {
    name: 'ArrowBigRight',
    Component: ArrowBigRight,
    source: 'lucide-react',
    tags: ['arrow', 'big', 'right'],
  },
  ArrowBigUp: {
    name: 'ArrowBigUp',
    Component: ArrowBigUp,
    source: 'lucide-react',
    tags: ['arrow', 'big', 'up'],
  },
  Asterisk: {
    name: 'Asterisk',
    Component: Asterisk,
    source: 'lucide-react',
    tags: ['asterisk', 'star', 'required'],
  },
  AtSign: {
    name: 'AtSign',
    Component: AtSign,
    source: 'lucide-react',
    tags: ['at', 'sign', 'email'],
  },
  Award: {
    name: 'Award',
    Component: Award,
    source: 'lucide-react',
    tags: ['award', 'badge', 'ribbon'],
  },
  Axe: {
    name: 'Axe',
    Component: Axe,
    source: 'lucide-react',
    tags: ['axe', 'tool', 'wood'],
  },
  Banknote: {
    name: 'Banknote',
    Component: Banknote,
    source: 'lucide-react',
    tags: ['banknote', 'money', 'cash'],
  },
  Beaker: {
    name: 'Beaker',
    Component: Beaker,
    source: 'lucide-react',
    tags: ['beaker', 'lab', 'science'],
  },
  BellRing: {
    name: 'BellRing',
    Component: BellRing,
    source: 'lucide-react',
    tags: ['bell', 'ring', 'notification'],
  },
  Bike: {
    name: 'Bike',
    Component: Bike,
    source: 'lucide-react',
    tags: ['bike', 'bicycle', 'transport'],
  },
  Binary: {
    name: 'Binary',
    Component: Binary,
    source: 'lucide-react',
    tags: ['binary', 'code', '01'],
  },
  Bitcoin: {
    name: 'Bitcoin',
    Component: Bitcoin,
    source: 'lucide-react',
    tags: ['bitcoin', 'crypto', 'currency'],
  },
  Bomb: {
    name: 'Bomb',
    Component: Bomb,
    source: 'lucide-react',
    tags: ['bomb', 'danger', 'explode'],
  },
  Bone: {
    name: 'Bone',
    Component: Bone,
    source: 'lucide-react',
    tags: ['bone', 'health', 'dog'],
  },
  Book: {
    name: 'Book',
    Component: Book,
    source: 'lucide-react',
    tags: ['book', 'read', 'library'],
  },
  Bookmark: {
    name: 'Bookmark',
    Component: Bookmark,
    source: 'lucide-react',
    tags: ['bookmark', 'save', 'favorite'],
  },
  Bot: {
    name: 'Bot',
    Component: Bot,
    source: 'lucide-react',
    tags: ['bot', 'robot', 'ai'],
  },
  Box: {
    name: 'Box',
    Component: Box,
    source: 'lucide-react',
    tags: ['box', 'package', 'container'],
  },
  Briefcase: {
    name: 'Briefcase',
    Component: Briefcase,
    source: 'lucide-react',
    tags: ['briefcase', 'work', 'business'],
  },
  Brush: {
    name: 'Brush',
    Component: Brush,
    source: 'lucide-react',
    tags: ['brush', 'paint', 'art'],
  },
  Calculator: {
    name: 'Calculator',
    Component: Calculator,
    source: 'lucide-react',
    tags: ['calculator', 'math', 'number'],
  },
  CalendarCheck: {
    name: 'CalendarCheck',
    Component: CalendarCheck,
    source: 'lucide-react',
    tags: ['calendar', 'check', 'date'],
  },
  CameraOff: {
    name: 'CameraOff',
    Component: CameraOff,
    source: 'lucide-react',
    tags: ['camera', 'off', 'disabled'],
  },
  CandlestickChart: {
    name: 'CandlestickChart',
    Component: CandlestickChart,
    source: 'lucide-react',
    tags: ['chart', 'candlestick', 'stock'],
  },
  Cast: {
    name: 'Cast',
    Component: Cast,
    source: 'lucide-react',
    tags: ['cast', 'stream', 'chromecast'],
  },
  Cat: {
    name: 'Cat',
    Component: Cat,
    source: 'lucide-react',
    tags: ['cat', 'animal', 'pet'],
  },
  Check: {
    name: 'Check',
    Component: Check,
    source: 'lucide-react',
    tags: ['check', 'done', 'tick'],
  },
  ChevronDown: {
    name: 'ChevronDown',
    Component: ChevronDown,
    source: 'lucide-react',
    tags: ['chevron', 'down', 'arrow'],
  },
  ChevronLeft: {
    name: 'ChevronLeft',
    Component: ChevronLeft,
    source: 'lucide-react',
    tags: ['chevron', 'left', 'arrow'],
  },
  ChevronRight: {
    name: 'ChevronRight',
    Component: ChevronRight,
    source: 'lucide-react',
    tags: ['chevron', 'right', 'arrow'],
  },
  ChevronUp: {
    name: 'ChevronUp',
    Component: ChevronUp,
    source: 'lucide-react',
    tags: ['chevron', 'up', 'arrow'],
  },
  ChevronsDown: {
    name: 'ChevronsDown',
    Component: ChevronsDown,
    source: 'lucide-react',
    tags: ['chevrons', 'down', 'arrows'],
  },
  ChevronsLeft: {
    name: 'ChevronsLeft',
    Component: ChevronsLeft,
    source: 'lucide-react',
    tags: ['chevrons', 'left', 'arrows'],
  },
  ChevronsRight: {
    name: 'ChevronsRight',
    Component: ChevronsRight,
    source: 'lucide-react',
    tags: ['chevrons', 'right', 'arrows'],
  },
  ChevronsUp: {
    name: 'ChevronsUp',
    Component: ChevronsUp,
    source: 'lucide-react',
    tags: ['chevrons', 'up', 'arrows'],
  },
  Chrome: {
    name: 'Chrome',
    Component: Chrome,
    source: 'lucide-react',
    tags: ['chrome', 'browser', 'google'],
  },
  Clipboard: {
    name: 'Clipboard',
    Component: Clipboard,
    source: 'lucide-react',
    tags: ['clipboard', 'copy', 'paste'],
  },
  CloudDrizzle: {
    name: 'CloudDrizzle',
    Component: CloudDrizzle,
    source: 'lucide-react',
    tags: ['cloud', 'drizzle', 'rain'],
  },
  CloudLightning: {
    name: 'CloudLightning',
    Component: CloudLightning,
    source: 'lucide-react',
    tags: ['cloud', 'lightning', 'storm'],
  },
  CloudRain: {
    name: 'CloudRain',
    Component: CloudRain,
    source: 'lucide-react',
    tags: ['cloud', 'rain', 'weather'],
  },
  CloudSnow: {
    name: 'CloudSnow',
    Component: CloudSnow,
    source: 'lucide-react',
    tags: ['cloud', 'snow', 'weather'],
  },
  Cog: {
    name: 'Cog',
    Component: Cog,
    source: 'lucide-react',
    tags: ['cog', 'gear', 'settings'],
  },
  Coins: {
    name: 'Coins',
    Component: Coins,
    source: 'lucide-react',
    tags: ['coins', 'money', 'currency'],
  },
  Columns: {
    name: 'Columns',
    Component: Columns,
    source: 'lucide-react',
    tags: ['columns', 'layout', 'grid'],
  },
  Command: {
    name: 'Command',
    Component: Command,
    source: 'lucide-react',
    tags: ['command', 'key', 'keyboard'],
  },
  Compass: {
    name: 'Compass',
    Component: Compass,
    source: 'lucide-react',
    tags: ['compass', 'direction', 'navigation'],
  },
  Contact: {
    name: 'Contact',
    Component: Contact,
    source: 'lucide-react',
    tags: ['contact', 'user', 'address book'],
  },
  Contrast: {
    name: 'Contrast',
    Component: Contrast,
    source: 'lucide-react',
    tags: ['contrast', 'brightness', 'theme'],
  },
  Cookie: {
    name: 'Cookie',
    Component: Cookie,
    source: 'lucide-react',
    tags: ['cookie', 'biscuit', 'privacy'],
  },
  Copyright: {
    name: 'Copyright',
    Component: Copyright,
    source: 'lucide-react',
    tags: ['copyright', 'license'],
  },
  CornerDownLeft: {
    name: 'CornerDownLeft',
    Component: CornerDownLeft,
    source: 'lucide-react',
    tags: ['corner', 'down', 'left', 'arrow'],
  },
  CornerDownRight: {
    name: 'CornerDownRight',
    Component: CornerDownRight,
    source: 'lucide-react',
    tags: ['corner', 'down', 'right', 'arrow'],
  },
  CornerLeftDown: {
    name: 'CornerLeftDown',
    Component: CornerLeftDown,
    source: 'lucide-react',
    tags: ['corner', 'left', 'down', 'arrow'],
  },
  CornerLeftUp: {
    name: 'CornerLeftUp',
    Component: CornerLeftUp,
    source: 'lucide-react',
    tags: ['corner', 'left', 'up', 'arrow'],
  },
  CornerRightDown: {
    name: 'CornerRightDown',
    Component: CornerRightDown,
    source: 'lucide-react',
    tags: ['corner', 'right', 'down', 'arrow'],
  },
  CornerRightUp: {
    name: 'CornerRightUp',
    Component: CornerRightUp,
    source: 'lucide-react',
    tags: ['corner', 'right', 'up', 'arrow'],
  },
  CornerUpLeft: {
    name: 'CornerUpLeft',
    Component: CornerUpLeft,
    source: 'lucide-react',
    tags: ['corner', 'up', 'left', 'arrow'],
  },
  CornerUpRight: {
    name: 'CornerUpRight',
    Component: CornerUpRight,
    source: 'lucide-react',
    tags: ['corner', 'up', 'right', 'arrow'],
  },
  Cpu: {
    name: 'Cpu',
    Component: Cpu,
    source: 'lucide-react',
    tags: ['cpu', 'processor', 'chip'],
  },
  CreativeCommons: {
    name: 'CreativeCommons',
    Component: CreativeCommons,
    source: 'lucide-react',
    tags: ['creative', 'commons', 'license'],
  },
  CreditCard: {
    name: 'CreditCard',
    Component: CreditCard,
    source: 'lucide-react',
    tags: ['credit', 'card', 'payment'],
  },
  Crop: {
    name: 'Crop',
    Component: Crop,
    source: 'lucide-react',
    tags: ['crop', 'image', 'edit'],
  },
  Cross: {
    name: 'Cross',
    Component: Cross,
    source: 'lucide-react',
    tags: ['cross', 'cancel', 'no'],
  },
  Crosshair: {
    name: 'Crosshair',
    Component: Crosshair,
    source: 'lucide-react',
    tags: ['crosshair', 'aim', 'target'],
  },
  Crown: {
    name: 'Crown',
    Component: Crown,
    source: 'lucide-react',
    tags: ['crown', 'king', 'queen'],
  },
  CupSoda: {
    name: 'CupSoda',
    Component: CupSoda,
    source: 'lucide-react',
    tags: ['cup', 'soda', 'drink'],
  },
  Currency: {
    name: 'Currency',
    Component: Currency,
    source: 'lucide-react',
    tags: ['currency', 'money', 'exchange'],
  },
  Database: {
    name: 'Database',
    Component: Database,
    source: 'lucide-react',
    tags: ['database', 'storage', 'server'],
  },
  Diamond: {
    name: 'Diamond',
    Component: Diamond,
    source: 'lucide-react',
    tags: ['diamond', 'gem', 'jewel'],
  },
  Dice1: {
    name: 'Dice1',
    Component: Dice1,
    source: 'lucide-react',
    tags: ['dice', '1', 'game'],
  },
  Dice2: {
    name: 'Dice2',
    Component: Dice2,
    source: 'lucide-react',
    tags: ['dice', '2', 'game'],
  },
  Dice3: {
    name: 'Dice3',
    Component: Dice3,
    source: 'lucide-react',
    tags: ['dice', '3', 'game'],
  },
  Dice4: {
    name: 'Dice4',
    Component: Dice4,
    source: 'lucide-react',
    tags: ['dice', '4', 'game'],
  },
  Dice5: {
    name: 'Dice5',
    Component: Dice5,
    source: 'lucide-react',
    tags: ['dice', '5', 'game'],
  },
  Dice6: {
    name: 'Dice6',
    Component: Dice6,
    source: 'lucide-react',
    tags: ['dice', '6', 'game'],
  },
  Disc: {
    name: 'Disc',
    Component: Disc,
    source: 'lucide-react',
    tags: ['disc', 'cd', 'vinyl'],
  },
  Dog: {
    name: 'Dog',
    Component: Dog,
    source: 'lucide-react',
    tags: ['dog', 'animal', 'pet'],
  },
  DollarSign: {
    name: 'DollarSign',
    Component: DollarSign,
    source: 'lucide-react',
    tags: ['dollar', 'sign', 'money'],
  },
  DoorClosed: {
    name: 'DoorClosed',
    Component: DoorClosed,
    source: 'lucide-react',
    tags: ['door', 'closed', 'exit'],
  },
  DoorOpen: {
    name: 'DoorOpen',
    Component: DoorOpen,
    source: 'lucide-react',
    tags: ['door', 'open', 'enter'],
  },
  Dribbble: {
    name: 'Dribbble',
    Component: Dribbble,
    source: 'lucide-react',
    tags: ['dribbble', 'social', 'design'],
  },
  Droplet: {
    name: 'Droplet',
    Component: Droplet,
    source: 'lucide-react',
    tags: ['droplet', 'water', 'drip'],
  },
  Eraser: {
    name: 'Eraser',
    Component: Eraser,
    source: 'lucide-react',
    tags: ['eraser', 'delete', 'remove'],
  },
  Euro: {
    name: 'Euro',
    Component: Euro,
    source: 'lucide-react',
    tags: ['euro', 'money', 'currency'],
  },
  ExternalLink: {
    name: 'ExternalLink',
    Component: ExternalLink,
    source: 'lucide-react',
    tags: ['external', 'link', 'new tab'],
  },
  Facebook: {
    name: 'Facebook',
    Component: Facebook,
    source: 'lucide-react',
    tags: ['facebook', 'social', 'meta'],
  },
  FastForward: {
    name: 'FastForward',
    Component: FastForward,
    source: 'lucide-react',
    tags: ['fast', 'forward', 'music'],
  },
  Feather: {
    name: 'Feather',
    Component: Feather,
    source: 'lucide-react',
    tags: ['feather', 'light', 'pen'],
  },
  Figma: {
    name: 'Figma',
    Component: Figma,
    source: 'lucide-react',
    tags: ['figma', 'design', 'tool'],
  },
  File: {
    name: 'File',
    Component: File,
    source: 'lucide-react',
    tags: ['file', 'document', 'page'],
  },
  FileArchive: {
    name: 'FileArchive',
    Component: FileArchive,
    source: 'lucide-react',
    tags: ['file', 'archive', 'zip'],
  },
  FileAudio: {
    name: 'FileAudio',
    Component: FileAudio,
    source: 'lucide-react',
    tags: ['file', 'audio', 'music'],
  },
  FileBadge: {
    name: 'FileBadge',
    Component: FileBadge,
    source: 'lucide-react',
    tags: ['file', 'badge', 'award'],
  },
  FileCheck: {
    name: 'FileCheck',
    Component: FileCheck,
    source: 'lucide-react',
    tags: ['file', 'check', 'done'],
  },
  FileCode: {
    name: 'FileCode',
    Component: FileCode,
    source: 'lucide-react',
    tags: ['file', 'code', 'developer'],
  },
  FileDigit: {
    name: 'FileDigit',
    Component: FileDigit,
    source: 'lucide-react',
    tags: ['file', 'digit', 'number'],
  },
  FileDown: {
    name: 'FileDown',
    Component: FileDown,
    source: 'lucide-react',
    tags: ['file', 'down', 'download'],
  },
  FileEdit: {
    name: 'FileEdit',
    Component: FileEdit,
    source: 'lucide-react',
    tags: ['file', 'edit', 'modify'],
  },
  FileHeart: {
    name: 'FileHeart',
    Component: FileHeart,
    source: 'lucide-react',
    tags: ['file', 'heart', 'favorite'],
  },
  FileImage: {
    name: 'FileImage',
    Component: FileImage,
    source: 'lucide-react',
    tags: ['file', 'image', 'photo'],
  },
  FileInput: {
    name: 'FileInput',
    Component: FileInput,
    source: 'lucide-react',
    tags: ['file', 'input', 'upload'],
  },
  FileJson: {
    name: 'FileJson',
    Component: FileJson,
    source: 'lucide-react',
    tags: ['file', 'json', 'data'],
  },
  FileKey: {
    name: 'FileKey',
    Component: FileKey,
    source: 'lucide-react',
    tags: ['file', 'key', 'secure'],
  },
  FileLock: {
    name: 'FileLock',
    Component: FileLock,
    source: 'lucide-react',
    tags: ['file', 'lock', 'private'],
  },
  FileMinus: {
    name: 'FileMinus',
    Component: FileMinus,
    source: 'lucide-react',
    tags: ['file', 'minus', 'remove'],
  },
  FileOutput: {
    name: 'FileOutput',
    Component: FileOutput,
    source: 'lucide-react',
    tags: ['file', 'output', 'export'],
  },
  FilePlus: {
    name: 'FilePlus',
    Component: FilePlus,
    source: 'lucide-react',
    tags: ['file', 'plus', 'add'],
  },
  FileQuestion: {
    name: 'FileQuestion',
    Component: FileQuestion,
    source: 'lucide-react',
    tags: ['file', 'question', 'help'],
  },
  FileScan: {
    name: 'FileScan',
    Component: FileScan,
    source: 'lucide-react',
    tags: ['file', 'scan', 'document'],
  },
  FileSearch: {
    name: 'FileSearch',
    Component: FileSearch,
    source: 'lucide-react',
    tags: ['file', 'search', 'find'],
  },
  FileSymlink: {
    name: 'FileSymlink',
    Component: FileSymlink,
    source: 'lucide-react',
    tags: ['file', 'symlink', 'shortcut'],
  },
  FileText: {
    name: 'FileText',
    Component: FileText,
    source: 'lucide-react',
    tags: ['file', 'text', 'document'],
  },
  FileUp: {
    name: 'FileUp',
    Component: FileUp,
    source: 'lucide-react',
    tags: ['file', 'up', 'upload'],
  },
  FileVideo: {
    name: 'FileVideo',
    Component: FileVideo,
    source: 'lucide-react',
    tags: ['file', 'video', 'movie'],
  },
  FileVolume: {
    name: 'FileVolume',
    Component: FileVolume,
    source: 'lucide-react',
    tags: ['file', 'volume', 'audio'],
  },
  FileWarning: {
    name: 'FileWarning',
    Component: FileWarning,
    source: 'lucide-react',
    tags: ['file', 'warning', 'alert'],
  },
  FileX: {
    name: 'FileX',
    Component: FileX,
    source: 'lucide-react',
    tags: ['file', 'x', 'delete'],
  },
  Files: {
    name: 'Files',
    Component: Files,
    source: 'lucide-react',
    tags: ['files', 'documents', 'multiple'],
  },
  Film: {
    name: 'Film',
    Component: Film,
    source: 'lucide-react',
    tags: ['film', 'movie', 'video'],
  },
  Flag: {
    name: 'Flag',
    Component: Flag,
    source: 'lucide-react',
    tags: ['flag', 'report', 'mark'],
  },
  Flame: {
    name: 'Flame',
    Component: Flame,
    source: 'lucide-react',
    tags: ['flame', 'fire', 'hot'],
  },
  Flashlight: {
    name: 'Flashlight',
    Component: Flashlight,
    source: 'lucide-react',
    tags: ['flashlight', 'torch', 'light'],
  },
  FlashlightOff: {
    name: 'FlashlightOff',
    Component: FlashlightOff,
    source: 'lucide-react',
    tags: ['flashlight', 'off'],
  },
  Folder: {
    name: 'Folder',
    Component: Folder,
    source: 'lucide-react',
    tags: ['folder', 'directory', 'files'],
  },
  FolderArchive: {
    name: 'FolderArchive',
    Component: FolderArchive,
    source: 'lucide-react',
    tags: ['folder', 'archive', 'zip'],
  },
  FolderCheck: {
    name: 'FolderCheck',
    Component: FolderCheck,
    source: 'lucide-react',
    tags: ['folder', 'check', 'done'],
  },
  FolderClock: {
    name: 'FolderClock',
    Component: FolderClock,
    source: 'lucide-react',
    tags: ['folder', 'clock', 'history'],
  },
  FolderClosed: {
    name: 'FolderClosed',
    Component: FolderClosed,
    source: 'lucide-react',
    tags: ['folder', 'closed'],
  },
  FolderCog: {
    name: 'FolderCog',
    Component: FolderCog,
    source: 'lucide-react',
    tags: ['folder', 'cog', 'settings'],
  },
  FolderDown: {
    name: 'FolderDown',
    Component: FolderDown,
    source: 'lucide-react',
    tags: ['folder', 'down', 'download'],
  },
  FolderEdit: {
    name: 'FolderEdit',
    Component: FolderEdit,
    source: 'lucide-react',
    tags: ['folder', 'edit', 'modify'],
  },
  FolderGit: {
    name: 'FolderGit',
    Component: FolderGit,
    source: 'lucide-react',
    tags: ['folder', 'git', 'version control'],
  },
  FolderGit2: {
    name: 'FolderGit2',
    Component: FolderGit2,
    source: 'lucide-react',
    tags: ['folder', 'git', 'version control'],
  },
  FolderHeart: {
    name: 'FolderHeart',
    Component: FolderHeart,
    source: 'lucide-react',
    tags: ['folder', 'heart', 'favorite'],
  },
  FolderInput: {
    name: 'FolderInput',
    Component: FolderInput,
    source: 'lucide-react',
    tags: ['folder', 'input', 'upload'],
  },
  FolderKey: {
    name: 'FolderKey',
    Component: FolderKey,
    source: 'lucide-react',
    tags: ['folder', 'key', 'secure'],
  },
  FolderLock: {
    name: 'FolderLock',
    Component: FolderLock,
    source: 'lucide-react',
    tags: ['folder', 'lock', 'private'],
  },
  FolderMinus: {
    name: 'FolderMinus',
    Component: FolderMinus,
    source: 'lucide-react',
    tags: ['folder', 'minus', 'remove'],
  },
  FolderOpen: {
    name: 'FolderOpen',
    Component: FolderOpen,
    source: 'lucide-react',
    tags: ['folder', 'open'],
  },
  FolderOutput: {
    name: 'FolderOutput',
    Component: FolderOutput,
    source: 'lucide-react',
    tags: ['folder', 'output', 'export'],
  },
  FolderPlus: {
    name: 'FolderPlus',
    Component: FolderPlus,
    source: 'lucide-react',
    tags: ['folder', 'plus', 'add'],
  },
  FolderRoot: {
    name: 'FolderRoot',
    Component: FolderRoot,
    source: 'lucide-react',
    tags: ['folder', 'root', 'main'],
  },
  FolderSearch: {
    name: 'FolderSearch',
    Component: FolderSearch,
    source: 'lucide-react',
    tags: ['folder', 'search', 'find'],
  },
  FolderSymlink: {
    name: 'FolderSymlink',
    Component: FolderSymlink,
    source: 'lucide-react',
    tags: ['folder', 'symlink', 'shortcut'],
  },
  FolderTree: {
    name: 'FolderTree',
    Component: FolderTree,
    source: 'lucide-react',
    tags: ['folder', 'tree', 'structure'],
  },
  FolderUp: {
    name: 'FolderUp',
    Component: FolderUp,
    source: 'lucide-react',
    tags: ['folder', 'up', 'upload'],
  },
  FolderX: {
    name: 'FolderX',
    Component: FolderX,
    source: 'lucide-react',
    tags: ['folder', 'x', 'delete'],
  },
  Folders: {
    name: 'Folders',
    Component: Folders,
    source: 'lucide-react',
    tags: ['folders', 'multiple', 'directories'],
  },
  Footprints: {
    name: 'Footprints',
    Component: Footprints,
    source: 'lucide-react',
    tags: ['footprints', 'steps', 'trace'],
  },
  Forklift: {
    name: 'Forklift',
    Component: Forklift,
    source: 'lucide-react',
    tags: ['forklift', 'logistics', 'warehouse'],
  },
  FormInput: {
    name: 'FormInput',
    Component: FormInput,
    source: 'lucide-react',
    tags: ['form', 'input', 'field'],
  },
  Forward: {
    name: 'Forward',
    Component: Forward,
    source: 'lucide-react',
    tags: ['forward', 'next', 'send'],
  },
  Frame: {
    name: 'Frame',
    Component: Frame,
    source: 'lucide-react',
    tags: ['frame', 'border', 'layout'],
  },
  Frown: {
    name: 'Frown',
    Component: Frown,
    source: 'lucide-react',
    tags: ['frown', 'sad', 'emoji'],
  },
  Fuel: {
    name: 'Fuel',
    Component: Fuel,
    source: 'lucide-react',
    tags: ['fuel', 'gas', 'station'],
  },
  FunctionSquare: {
    name: 'FunctionSquare',
    Component: FunctionSquare,
    source: 'lucide-react',
    tags: ['function', 'code', 'math'],
  },
  Gamepad: {
    name: 'Gamepad',
    Component: Gamepad,
    source: 'lucide-react',
    tags: ['gamepad', 'controller', 'game'],
  },
  Gamepad2: {
    name: 'Gamepad2',
    Component: Gamepad2,
    source: 'lucide-react',
    tags: ['gamepad', 'controller', 'game'],
  },
  Gauge: {
    name: 'Gauge',
    Component: Gauge,
    source: 'lucide-react',
    tags: ['gauge', 'dashboard', 'speed'],
  },
  Gavel: {
    name: 'Gavel',
    Component: Gavel,
    source: 'lucide-react',
    tags: ['gavel', 'judge', 'law'],
  },
  Gem: {
    name: 'Gem',
    Component: Gem,
    source: 'lucide-react',
    tags: ['gem', 'diamond', 'jewel'],
  },
  Ghost: {
    name: 'Ghost',
    Component: Ghost,
    source: 'lucide-react',
    tags: ['ghost', 'halloween', 'spirit'],
  },
  Gift: {
    name: 'Gift',
    Component: Gift,
    source: 'lucide-react',
    tags: ['gift', 'present', 'box'],
  },
  GitBranch: {
    name: 'GitBranch',
    Component: GitBranch,
    source: 'lucide-react',
    tags: ['git', 'branch', 'version'],
  },
  GitBranchPlus: {
    name: 'GitBranchPlus',
    Component: GitBranchPlus,
    source: 'lucide-react',
    tags: ['git', 'branch', 'plus'],
  },
  GitCommit: {
    name: 'GitCommit',
    Component: GitCommit,
    source: 'lucide-react',
    tags: ['git', 'commit', 'version'],
  },
  GitCompare: {
    name: 'GitCompare',
    Component: GitCompare,
    source: 'lucide-react',
    tags: ['git', 'compare', 'diff'],
  },
  GitFork: {
    name: 'GitFork',
    Component: GitFork,
    source: 'lucide-react',
    tags: ['git', 'fork', 'branch'],
  },
  GitMerge: {
    name: 'GitMerge',
    Component: GitMerge,
    source: 'lucide-react',
    tags: ['git', 'merge', 'branch'],
  },
  GitPullRequest: {
    name: 'GitPullRequest',
    Component: GitPullRequest,
    source: 'lucide-react',
    tags: ['git', 'pull', 'request'],
  },
  GitPullRequestClosed: {
    name: 'GitPullRequestClosed',
    Component: GitPullRequestClosed,
    source: 'lucide-react',
    tags: ['git', 'pull', 'closed'],
  },
  GitPullRequestDraft: {
    name: 'GitPullRequestDraft',
    Component: GitPullRequestDraft,
    source: 'lucide-react',
    tags: ['git', 'pull', 'draft'],
  },
  Github: {
    name: 'Github',
    Component: Github,
    source: 'lucide-react',
    tags: ['github', 'social', 'code'],
  },
  Gitlab: {
    name: 'Gitlab',
    Component: Gitlab,
    source: 'lucide-react',
    tags: ['gitlab', 'social', 'code'],
  },
  GlassWater: {
    name: 'GlassWater',
    Component: GlassWater,
    source: 'lucide-react',
    tags: ['glass', 'water', 'drink'],
  },
  Glasses: {
    name: 'Glasses',
    Component: Glasses,
    source: 'lucide-react',
    tags: ['glasses', 'spectacles', 'vision'],
  },
  Globe2: {
    name: 'Globe2',
    Component: Globe2,
    source: 'lucide-react',
    tags: ['globe', 'world', 'earth'],
  },
  Grab: {
    name: 'Grab',
    Component: Grab,
    source: 'lucide-react',
    tags: ['grab', 'hand', 'move'],
  },
  GraduationCap: {
    name: 'GraduationCap',
    Component: GraduationCap,
    source: 'lucide-react',
    tags: ['graduation', 'cap', 'school'],
  },
  Grape: {
    name: 'Grape',
    Component: Grape,
    source: 'lucide-react',
    tags: ['grape', 'fruit', 'food'],
  },
  Grid: {
    name: 'Grid',
    Component: Grid,
    source: 'lucide-react',
    tags: ['grid', 'layout', 'table'],
  },
  GripHorizontal: {
    name: 'GripHorizontal',
    Component: GripHorizontal,
    source: 'lucide-react',
    tags: ['grip', 'horizontal', 'drag'],
  },
  GripVertical: {
    name: 'GripVertical',
    Component: GripVertical,
    source: 'lucide-react',
    tags: ['grip', 'vertical', 'drag'],
  },
  Hammer: {
    name: 'Hammer',
    Component: Hammer,
    source: 'lucide-react',
    tags: ['hammer', 'tool', 'build'],
  },
  Hand: {
    name: 'Hand',
    Component: Hand,
    source: 'lucide-react',
    tags: ['hand', 'stop', 'grab'],
  },
  HandMetal: {
    name: 'HandMetal',
    Component: HandMetal,
    source: 'lucide-react',
    tags: ['hand', 'metal', 'rock'],
  },
  HardDrive: {
    name: 'HardDrive',
    Component: HardDrive,
    source: 'lucide-react',
    tags: ['hard', 'drive', 'storage'],
  },
  HardHat: {
    name: 'HardHat',
    Component: HardHat,
    source: 'lucide-react',
    tags: ['hard', 'hat', 'construction'],
  },
  Hash: {
    name: 'Hash',
    Component: Hash,
    source: 'lucide-react',
    tags: ['hash', 'tag', 'number'],
  },
  Haze: {
    name: 'Haze',
    Component: Haze,
    source: 'lucide-react',
    tags: ['haze', 'fog', 'weather'],
  },
  Heading: {
    name: 'Heading',
    Component: Heading,
    source: 'lucide-react',
    tags: ['heading', 'title', 'text'],
  },
  Heading1: {
    name: 'Heading1',
    Component: Heading1,
    source: 'lucide-react',
    tags: ['heading', 'h1', 'title'],
  },
  Heading2: {
    name: 'Heading2',
    Component: Heading2,
    source: 'lucide-react',
    tags: ['heading', 'h2', 'title'],
  },
  Heading3: {
    name: 'Heading3',
    Component: Heading3,
    source: 'lucide-react',
    tags: ['heading', 'h3', 'title'],
  },
  Heading4: {
    name: 'Heading4',
    Component: Heading4,
    source: 'lucide-react',
    tags: ['heading', 'h4', 'title'],
  },
  Heading5: {
    name: 'Heading5',
    Component: Heading5,
    source: 'lucide-react',
    tags: ['heading', 'h5', 'title'],
  },
  Heading6: {
    name: 'Heading6',
    Component: Heading6,
    source: 'lucide-react',
    tags: ['heading', 'h6', 'title'],
  },
  Headphones: {
    name: 'Headphones',
    Component: Headphones,
    source: 'lucide-react',
    tags: ['headphones', 'music', 'audio'],
  },
  HeartCrack: {
    name: 'HeartCrack',
    Component: HeartCrack,
    source: 'lucide-react',
    tags: ['heart', 'crack', 'break'],
  },
  HeartHandshake: {
    name: 'HeartHandshake',
    Component: HeartHandshake,
    source: 'lucide-react',
    tags: ['heart', 'handshake', 'deal'],
  },
  HeartOff: {
    name: 'HeartOff',
    Component: HeartOff,
    source: 'lucide-react',
    tags: ['heart', 'off', 'dislike'],
  },
  HelpCircle: {
    name: 'HelpCircle',
    Component: HelpCircle,
    source: 'lucide-react',
    tags: ['help', 'circle', 'question'],
  },
  HelpingHand: {
    name: 'HelpingHand',
    Component: HelpingHand,
    source: 'lucide-react',
    tags: ['helping', 'hand', 'support'],
  },
  Hexagon: {
    name: 'Hexagon',
    Component: Hexagon,
    source: 'lucide-react',
    tags: ['hexagon', 'shape', 'geometry'],
  },
  Highlighter: {
    name: 'Highlighter',
    Component: Highlighter,
    source: 'lucide-react',
    tags: ['highlighter', 'mark', 'pen'],
  },
  History: {
    name: 'History',
    Component: History,
    source: 'lucide-react',
    tags: ['history', 'time', 'clock'],
  },
  Hotel: {
    name: 'Hotel',
    Component: Hotel,
    source: 'lucide-react',
    tags: ['hotel', 'building', 'bed'],
  },
  Hourglass: {
    name: 'Hourglass',
    Component: Hourglass,
    source: 'lucide-react',
    tags: ['hourglass', 'time', 'sand'],
  },
  IceCream: {
    name: 'IceCream',
    Component: IceCream,
    source: 'lucide-react',
    tags: ['ice', 'cream', 'dessert'],
  },
  Image: {
    name: 'Image',
    Component: Image,
    source: 'lucide-react',
    tags: ['image', 'photo', 'picture'],
  },
  ImageMinus: {
    name: 'ImageMinus',
    Component: ImageMinus,
    source: 'lucide-react',
    tags: ['image', 'minus', 'remove'],
  },
  ImageOff: {
    name: 'ImageOff',
    Component: ImageOff,
    source: 'lucide-react',
    tags: ['image', 'off', 'disabled'],
  },
  ImagePlus: {
    name: 'ImagePlus',
    Component: ImagePlus,
    source: 'lucide-react',
    tags: ['image', 'plus', 'add'],
  },
  Import: {
    name: 'Import',
    Component: Import,
    source: 'lucide-react',
    tags: ['import', 'download', 'login'],
  },
  Inbox: {
    name: 'Inbox',
    Component: Inbox,
    source: 'lucide-react',
    tags: ['inbox', 'mail', 'email'],
  },
  Indent: {
    name: 'Indent',
    Component: Indent,
    source: 'lucide-react',
    tags: ['indent', 'text', 'align'],
  },
  IndianRupee: {
    name: 'IndianRupee',
    Component: IndianRupee,
    source: 'lucide-react',
    tags: ['indian', 'rupee', 'money'],
  },
  Info: {
    name: 'Info',
    Component: Info,
    source: 'lucide-react',
    tags: ['info', 'information', 'about'],
  },
  Inspect: {
    name: 'Inspect',
    Component: Inspect,
    source: 'lucide-react',
    tags: ['inspect', 'search', 'find'],
  },
  Instagram: {
    name: 'Instagram',
    Component: Instagram,
    source: 'lucide-react',
    tags: ['instagram', 'social', 'photo'],
  },
  Italic: {
    name: 'Italic',
    Component: Italic,
    source: 'lucide-react',
    tags: ['italic', 'text', 'format'],
  },
  IterationCcw: {
    name: 'IterationCcw',
    Component: IterationCcw,
    source: 'lucide-react',
    tags: ['iteration', 'ccw', 'repeat'],
  },
  IterationCw: {
    name: 'IterationCw',
    Component: IterationCw,
    source: 'lucide-react',
    tags: ['iteration', 'cw', 'repeat'],
  },
  JapaneseYen: {
    name: 'JapaneseYen',
    Component: JapaneseYen,
    source: 'lucide-react',
    tags: ['japanese', 'yen', 'money'],
  },
  Joystick: {
    name: 'Joystick',
    Component: Joystick,
    source: 'lucide-react',
    tags: ['joystick', 'game', 'controller'],
  },
  Key: {
    name: 'Key',
    Component: Key,
    source: 'lucide-react',
    tags: ['key', 'password', 'secure'],
  },
  Keyboard: {
    name: 'Keyboard',
    Component: Keyboard,
    source: 'lucide-react',
    tags: ['keyboard', 'type', 'input'],
  },
  Lamp: {
    name: 'Lamp',
    Component: Lamp,
    source: 'lucide-react',
    tags: ['lamp', 'light', 'bulb'],
  },
  LampCeiling: {
    name: 'LampCeiling',
    Component: LampCeiling,
    source: 'lucide-react',
    tags: ['lamp', 'ceiling', 'light'],
  },
  LampDesk: {
    name: 'LampDesk',
    Component: LampDesk,
    source: 'lucide-react',
    tags: ['lamp', 'desk', 'light'],
  },
  LampFloor: {
    name: 'LampFloor',
    Component: LampFloor,
    source: 'lucide-react',
    tags: ['lamp', 'floor', 'light'],
  },
  LampWallDown: {
    name: 'LampWallDown',
    Component: LampWallDown,
    source: 'lucide-react',
    tags: ['lamp', 'wall', 'down'],
  },
  LampWallUp: {
    name: 'LampWallUp',
    Component: LampWallUp,
    source: 'lucide-react',
    tags: ['lamp', 'wall', 'up'],
  },
  Landmark: {
    name: 'Landmark',
    Component: Landmark,
    source: 'lucide-react',
    tags: ['landmark', 'building', 'bank'],
  },
  Languages: {
    name: 'Languages',
    Component: Languages,
    source: 'lucide-react',
    tags: ['languages', 'translate', 'i18n'],
  },
  Laptop: {
    name: 'Laptop',
    Component: Laptop,
    source: 'lucide-react',
    tags: ['laptop', 'computer', 'device'],
  },
  Laptop2: {
    name: 'Laptop2',
    Component: Laptop2,
    source: 'lucide-react',
    tags: ['laptop', 'computer', 'device'],
  },
  Lasso: {
    name: 'Lasso',
    Component: Lasso,
    source: 'lucide-react',
    tags: ['lasso', 'select', 'tool'],
  },
  LassoSelect: {
    name: 'LassoSelect',
    Component: LassoSelect,
    source: 'lucide-react',
    tags: ['lasso', 'select', 'tool'],
  },
  Laugh: {
    name: 'Laugh',
    Component: Laugh,
    source: 'lucide-react',
    tags: ['laugh', 'happy', 'emoji'],
  },
  Layers: {
    name: 'Layers',
    Component: Layers,
    source: 'lucide-react',
    tags: ['layers', 'stack', 'design'],
  },
}
