server:
  port: 10500

# ??? ?? ?????? ?? ??
spring:
  # ?????? ?? ??
  application:
    name: chat-back
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${db.ip}:${db.port}/${db.database}
    username: ${db.username}
    password: ${db.password}
    # Hikari Connection Pool ??
    hikari:
      # ?? ?? ??? ?.
      minimum-idle: 2
      # ?? ??? ? ??. **?? ??: 1? ?? ?? ?? ??? ??? ? ????. ?? 10 ???? ???? ?? ?????.**
      maximum-pool-size: 10
      # JDBC ???? ??
      data-source-properties:
        # ??(Batch) ???? ? ?? ??? ?? rewriteBatchedStatements ?? ???
        rewriteBatchedStatements: true
  # Spring Data JPA ?? ??
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      # ??: ImprovedNamingStrategy? ?????, ?? Spring Boot??? SpringPhysicalNamingStrategy? ???? ?? ??????.
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        # ??? ID ??? ?? ?? ??
        use-new-id-generator-mappings: true
    properties:
      hibernate:
        format_sql: true
        # JDBC ?? ?? ??. ?? SQL? ??? ???? ?? ??
        jdbc:
          batch_size: 300
          fetch_size: 30
    # ???? SQL ??? ??? ???? ??. (?? ????? true? ???? ?? ??)
    show-sql: true

# ?????? ?? ??? ?? ??? ????
db:
  ip: localhost
  port: 5432
  database: postgres
  username: postgres
  password: ${DB_PASSWORD:1234asd}